if global.state = 0
    sprite_index = spr_mario_small_warp
if global.state = 1
    sprite_index = spr_mario_big_warp
if global.state = 2
    sprite_index = spr_mario_fire_warp
if global.state = 3
    sprite_index = spr_mario_hammer_warp
if global.state = 4
    sprite_index = spr_mario_leaf_warp
if global.state = 5
    sprite_index = spr_mario_tanooki_warp
if global.state = 6
    sprite_index = spr_mario_frog_warp
if global.state = 7
    sprite_index = spr_mario_bomb_warp
if global.state = 8
    sprite_index = spr_mario_ice_warp
if global.state = 9
    sprite_index = spr_mario_super_warp
if global.state = 10
    sprite_index = spr_mario_carrot_warp
if global.state = 11
    sprite_index = spr_mario_ninja_warp
if global.state = 12
    sprite_index = spr_mario_bee_warp
if global.state = 13
    sprite_index = spr_mario_shell_warp
if global.state = 14
    sprite_index = spr_mario_penguin_warp
