if global.state = 0
    sprite_index = spr_mario_small_climb
if global.state = 1
    sprite_index = spr_mario_big_climb
if global.state = 2
    sprite_index = spr_mario_fire_climb
if global.state = 3
    sprite_index = spr_mario_hammer_climb
if global.state = 4
    sprite_index = spr_mario_leaf_climb
if global.state = 5
    sprite_index = spr_mario_tanooki_climb
if global.state = 6
    sprite_index = spr_mario_frog_climb
if global.state = 7
    sprite_index = spr_mario_bomb_climb
if global.state = 8
    sprite_index = spr_mario_ice_climb
if global.state = 9
    sprite_index = spr_mario_super_climb
if global.state = 10
    sprite_index = spr_mario_carrot_climb
if global.state = 11
    sprite_index = spr_mario_ninja_climb
if global.state = 12
    sprite_index = spr_mario_bee_climb
if global.state = 13
    sprite_index = spr_mario_shell_climb
if global.state = 14
    sprite_index = spr_mario_penguin_climb
