if global.state = 0
    sprite_index = spr_mario_small_slide
if global.state = 1
    sprite_index = spr_mario_big_slide
if global.state = 2
    sprite_index = spr_mario_fire_slide
if global.state = 3
    sprite_index = spr_mario_hammer_slide
if global.state = 4
    sprite_index = spr_mario_leaf_slide
if global.state = 5
    sprite_index = spr_mario_tanooki_slide
if global.state = 6
    sprite_index = spr_mario_frog_slide
if global.state = 7
    sprite_index = spr_mario_bomb_slide
if global.state = 8
    sprite_index = spr_mario_ice_slide
if global.state = 9
    sprite_index = spr_mario_super_slide
if global.state = 10
    sprite_index = spr_mario_carrot_slide
if global.state = 11
    sprite_index = spr_mario_ninja_slide
if global.state = 12
    sprite_index = spr_mario_bee_slide
if global.state = 13
    sprite_index = spr_mario_shell_slide
if global.state = 14
    sprite_index = spr_mario_penguin_slide
